### ISSUE TITLE
SparkyCI build fails

### ISSUE THREAD

**Issue by melezhik** [perl6/Documentable#165]
Hi! 

Here is SparkyCI report - http://sparrowhub.io:2222/report/270, UI has a bug not showing correctly html like symbols but the error is:

```
Failed to find dependencies: node:from<bin>, dot:from<bin>
```

**Comment by melezhik** [comment]
Oh, wait a second, looks like this is  a way in which `zef` inform that `node` and `dot` binaries are missing on the target platform, right?

**Comment by melezhik** [comment]
btw, what do those correspond to?

* `node:from<bin>` - Nodejs and npm?
* `dot:from<bin>` - what is that?

**Comment by JJ** [comment]
node is needed for syntax highlighting, and dot for generation of dependency graphs.
