### ISSUE TITLE
Can't install module

### ISSUE THREAD

**Issue by coke** [perl6/Documentable#29]
Pod::To::Cached (a dependency of this module) has failures, so I cannot install Documentable. 

https://github.com/finanalyst/pod-cached/issues/25

**Comment by tbrowder** [comment]
I have the same problem, i.e., still unable to find missing dependencies.

I also have other concerns, such as how user-desires for section and topic names and order are entered, but those issues may be resolved if I can get an operable installation.

**Comment by antoniogamiz** [comment]
Have you tried to install the most recent version of Pod::To::Cached? Try it with:

`zef install https://github.com/perl6/Pod-To-Cached.git`

I do not know what may be causing this problem, I can install it without problems. It can be installed without any errors in the CI environments, too... mmm

**Comment by tbrowder** [comment]
My attempt showed missing dependencies on two other modules:

    Pod::TypeGraph
    Pod::Utilities

**Comment by antoniogamiz** [comment]
'Pod::TypeGraph'? That dependency does not exist I think. Did you mean 'Perl6::TypeGraph'?

I have executed: 

~~~
zef install --force-install Perl6::TypeGraph
zef install --force-install Pod::Utilities
~~~

right now and they work fine. Have you upgraded zef?

**Comment by tbrowder** [comment]
Sorry for the wrong name (Perl6::TypeGraph). I have upgraded zef now, but still have the same problem. I will force-install those two missing modules.

**Comment by antoniogamiz** [comment]
Mmm is very strange that zef does not find those modules.

**Comment by coke** [comment]
The install command suggested by @antoniogamiz fails as well:

```
$ zef install https://github.com/perl6/Pod-To-Cached.git
===> Testing: Pod::To::Cached:ver<0.3.4>:auth<finanalyst>
# Failed test 'One current, one tainted'
# at t/020-source.t line 156
# expected: ${:a-pod-file("Valid"), :a-second-pod-file("Current")}
#      got: ${:a-pod-file("Current"), :a-second-pod-file("Current")}
# Failed test 'One remains Valid because new version did not compile'
# at t/020-source.t line 159
# expected: ${:a-pod-file("Valid"), :a-second-pod-file("Current")}
#      got: ${:a-pod-file("Current"), :a-second-pod-file("Current")}
# Failed test 'Error detected in pod'
# at t/020-source.t line 161
# expected a match with: /'Compile error'/
#                   got: ""
# Failed test 'new file not added to cache because it did not compile'
# at t/020-source.t line 168
# You failed 4 tests of 36
# test pod extraction
# testing freeze
# Heavy duty test optional
===> Testing [FAIL]: Pod::To::Cached:ver<0.3.4>:auth<finanalyst>
Aborting due to test failure: Pod::To::Cached:ver<0.3.4>:auth<finanalyst> (use --force-test to override)
```

**Comment by antoniogamiz** [comment]
Mm, I can only think of a problem with the perl6 version. 

I'm using:

~~~
$ perl6 --version
This is Rakudo version 2019.07.1 built on MoarVM version 2019.07.1
implementing Perl 6.d.
~~~

Or maybe is a problem with directory permissions, I do not have a clue. Mmm

**Comment by antoniogamiz** [comment]
I have asked in IRC for people to get installed this module and they can install it without problems. Link [here](https://colabti.org/irclogger/irclogger_log/perl6?date=2019-09-02#l495). 

@vrug is using the HEAD version so it's not a problem with the perl6 version.

**Comment by tbrowder** [comment]
Are they in the ecosystem?

**Comment by antoniogamiz** [comment]
Yep

- [Pod::Utilities](https://github.com/perl6/ecosystem/blob/a050420ea665139a173cd5b0b9557ecb5f0b1ba0/META.list#L866)
- [Perl6::TypeGraph](https://github.com/perl6/ecosystem/blob/a050420ea665139a173cd5b0b9557ecb5f0b1ba0/META.list#L865)

**Comment by JJ** [comment]
Is it OSx?

**Comment by coke** [comment]
Yes, this is OS X.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87
```

**Comment by antoniogamiz** [comment]
I think this has already been resolved in the new version of Pod::To::Cached. @coke can you confirm?

**Comment by JJ** [comment]
We should probably update the version requirements for Documentable, as
well as add AppVeyor to check.

**Comment by coke** [comment]
```zef install Pod::To::Cached``` now works on my machine.
