### ISSUE TITLE
Assets are still downloaded from the old repo

### ISSUE THREAD

**Issue by JJ** [perl6/Documentable#35]
They should get moved to the new one and tagged with the new release. As a matter of fact, since we can obtain the release from `$*RESOURCES` we should probably get the right version for that thing.
This is related to #33

**Comment by antoniogamiz** [comment]
What do you mean by 'the right version of that thing'?

**Comment by JJ** [comment]
A version that matches the one in META6.json.

**Comment by antoniogamiz** [comment]
We still have the problem with the releases at the changes in the patch version. Or do you mean download those assets that match with the major and minor version numbers?

**Comment by JJ** [comment]
Well, that would be nice, but actually the main thing is to download them
from this repository, not the old one.

**Comment by antoniogamiz** [comment]
Ok. In addition, I have improved the setup command to avoid overriding files.
